<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>data quality assessment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="data-quality-assessment_files/libs/clipboard/clipboard.min.js"></script>
<script src="data-quality-assessment_files/libs/quarto-html/quarto.js"></script>
<script src="data-quality-assessment_files/libs/quarto-html/popper.min.js"></script>
<script src="data-quality-assessment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="data-quality-assessment_files/libs/quarto-html/anchor.min.js"></script>
<link href="data-quality-assessment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="data-quality-assessment_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="data-quality-assessment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="data-quality-assessment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="data-quality-assessment_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#import-libraries" id="toc-import-libraries" class="nav-link active" data-scroll-target="#import-libraries">Import libraries</a></li>
  <li><a href="#read-in-files" id="toc-read-in-files" class="nav-link" data-scroll-target="#read-in-files">Read in files</a></li>
  <li><a href="#data-at-first-glance" id="toc-data-at-first-glance" class="nav-link" data-scroll-target="#data-at-first-glance">Data at first glance</a></li>
  <li><a href="#clean-customerdemographic" id="toc-clean-customerdemographic" class="nav-link" data-scroll-target="#clean-customerdemographic">Clean CustomerDemographic</a>
  <ul class="collapse">
  <li><a href="#dob" id="toc-dob" class="nav-link" data-scroll-target="#dob">DOB</a></li>
  <li><a href="#customer_id" id="toc-customer_id" class="nav-link" data-scroll-target="#customer_id">customer_id</a></li>
  <li><a href="#gender" id="toc-gender" class="nav-link" data-scroll-target="#gender">gender</a></li>
  <li><a href="#first_name-and-last_name" id="toc-first_name-and-last_name" class="nav-link" data-scroll-target="#first_name-and-last_name">first_name and last_name</a></li>
  <li><a href="#past_3_years_bike_related_purchases" id="toc-past_3_years_bike_related_purchases" class="nav-link" data-scroll-target="#past_3_years_bike_related_purchases">past_3_years_bike_related_purchases</a></li>
  <li><a href="#job_title" id="toc-job_title" class="nav-link" data-scroll-target="#job_title">job_title</a></li>
  <li><a href="#job_industry_category" id="toc-job_industry_category" class="nav-link" data-scroll-target="#job_industry_category">job_industry_category</a></li>
  <li><a href="#wealth_segment" id="toc-wealth_segment" class="nav-link" data-scroll-target="#wealth_segment">wealth_segment</a></li>
  <li><a href="#deceased_indicator" id="toc-deceased_indicator" class="nav-link" data-scroll-target="#deceased_indicator">deceased_indicator</a></li>
  <li><a href="#default" id="toc-default" class="nav-link" data-scroll-target="#default">default</a></li>
  <li><a href="#owns_car" id="toc-owns_car" class="nav-link" data-scroll-target="#owns_car">owns_car</a></li>
  <li><a href="#tenure" id="toc-tenure" class="nav-link" data-scroll-target="#tenure">tenure</a></li>
  </ul></li>
  <li><a href="#clean-customeraddress" id="toc-clean-customeraddress" class="nav-link" data-scroll-target="#clean-customeraddress">Clean CustomerAddress</a>
  <ul class="collapse">
  <li><a href="#customer_id-1" id="toc-customer_id-1" class="nav-link" data-scroll-target="#customer_id-1">customer_id</a></li>
  <li><a href="#address" id="toc-address" class="nav-link" data-scroll-target="#address">address</a></li>
  <li><a href="#postcode" id="toc-postcode" class="nav-link" data-scroll-target="#postcode">postcode</a></li>
  <li><a href="#state" id="toc-state" class="nav-link" data-scroll-target="#state">state</a></li>
  <li><a href="#country" id="toc-country" class="nav-link" data-scroll-target="#country">country</a></li>
  <li><a href="#property_valuation" id="toc-property_valuation" class="nav-link" data-scroll-target="#property_valuation">property_valuation</a></li>
  </ul></li>
  <li><a href="#clean-transactions" id="toc-clean-transactions" class="nav-link" data-scroll-target="#clean-transactions">Clean Transactions</a>
  <ul class="collapse">
  <li><a href="#transaction_date" id="toc-transaction_date" class="nav-link" data-scroll-target="#transaction_date">transaction_date</a></li>
  <li><a href="#transaction_id" id="toc-transaction_id" class="nav-link" data-scroll-target="#transaction_id">transaction_id</a></li>
  <li><a href="#product_id" id="toc-product_id" class="nav-link" data-scroll-target="#product_id">product_id</a></li>
  <li><a href="#customer_id-2" id="toc-customer_id-2" class="nav-link" data-scroll-target="#customer_id-2">customer_id</a></li>
  <li><a href="#product_first_sold_date" id="toc-product_first_sold_date" class="nav-link" data-scroll-target="#product_first_sold_date">product_first_sold_date</a></li>
  <li><a href="#online_order" id="toc-online_order" class="nav-link" data-scroll-target="#online_order">online_order</a></li>
  <li><a href="#order_status" id="toc-order_status" class="nav-link" data-scroll-target="#order_status">order_status</a></li>
  <li><a href="#brand" id="toc-brand" class="nav-link" data-scroll-target="#brand">brand</a></li>
  <li><a href="#product_line" id="toc-product_line" class="nav-link" data-scroll-target="#product_line">product_line</a></li>
  <li><a href="#product_class" id="toc-product_class" class="nav-link" data-scroll-target="#product_class">product_class</a></li>
  <li><a href="#product_size" id="toc-product_size" class="nav-link" data-scroll-target="#product_size">product_size</a></li>
  <li><a href="#product_size-1" id="toc-product_size-1" class="nav-link" data-scroll-target="#product_size-1">product_size</a></li>
  <li><a href="#standard_cost" id="toc-standard_cost" class="nav-link" data-scroll-target="#standard_cost">standard_cost</a></li>
  <li><a href="#list_price" id="toc-list_price" class="nav-link" data-scroll-target="#list_price">list_price</a></li>
  </ul></li>
  <li><a href="#clean-newcustomerlist" id="toc-clean-newcustomerlist" class="nav-link" data-scroll-target="#clean-newcustomerlist">Clean NewCustomerList</a>
  <ul class="collapse">
  <li><a href="#past_3_years_bike_related_purchases-1" id="toc-past_3_years_bike_related_purchases-1" class="nav-link" data-scroll-target="#past_3_years_bike_related_purchases-1">past_3_years_bike_related_purchases</a></li>
  <li><a href="#property_valuation-1" id="toc-property_valuation-1" class="nav-link" data-scroll-target="#property_valuation-1">property_valuation</a></li>
  <li><a href="#first_name" id="toc-first_name" class="nav-link" data-scroll-target="#first_name">first_name</a></li>
  <li><a href="#last_name" id="toc-last_name" class="nav-link" data-scroll-target="#last_name">last_name</a></li>
  <li><a href="#dob-1" id="toc-dob-1" class="nav-link" data-scroll-target="#dob-1">DOB</a></li>
  <li><a href="#gender-1" id="toc-gender-1" class="nav-link" data-scroll-target="#gender-1">gender</a></li>
  <li><a href="#job_title-1" id="toc-job_title-1" class="nav-link" data-scroll-target="#job_title-1">job_title</a></li>
  <li><a href="#job_industry_category-1" id="toc-job_industry_category-1" class="nav-link" data-scroll-target="#job_industry_category-1">job_industry_category</a></li>
  <li><a href="#wealth_segment-1" id="toc-wealth_segment-1" class="nav-link" data-scroll-target="#wealth_segment-1">wealth_segment</a></li>
  <li><a href="#deceased_indicator-1" id="toc-deceased_indicator-1" class="nav-link" data-scroll-target="#deceased_indicator-1">deceased_indicator</a></li>
  <li><a href="#owns_car-1" id="toc-owns_car-1" class="nav-link" data-scroll-target="#owns_car-1">owns_car</a></li>
  <li><a href="#tenure-1" id="toc-tenure-1" class="nav-link" data-scroll-target="#tenure-1">tenure</a></li>
  <li><a href="#address-1" id="toc-address-1" class="nav-link" data-scroll-target="#address-1">address</a></li>
  <li><a href="#state-1" id="toc-state-1" class="nav-link" data-scroll-target="#state-1">state</a></li>
  <li><a href="#postcode-1" id="toc-postcode-1" class="nav-link" data-scroll-target="#postcode-1">postcode</a></li>
  <li><a href="#country-1" id="toc-country-1" class="nav-link" data-scroll-target="#country-1">country</a></li>
  </ul></li>
  <li><a href="#export-cleansed-csv-files" id="toc-export-cleansed-csv-files" class="nav-link" data-scroll-target="#export-cleansed-csv-files">Export cleansed csv files</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">data quality assessment</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="import-libraries" class="level2">
<h2 class="anchored" data-anchor-id="import-libraries">Import libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DataExplorer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="read-in-files" class="level2">
<h2 class="anchored" data-anchor-id="read-in-files">Read in files</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Task 1/KPMG_VI_New_raw_data_update_final.xlsx"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">sheet =</span> <span class="st">"CustomerDemographic"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">col_types =</span> <span class="fu">c</span>(<span class="st">"text"</span>,<span class="st">"text"</span>,<span class="st">"text"</span>,<span class="st">"text"</span>, <span class="st">"numeric"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"date"</span>, <span class="st">"text"</span>,<span class="st">"text"</span>,<span class="st">"text"</span>,<span class="st">"text"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"text"</span>,<span class="st">"text"</span>,<span class="st">"numeric"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting date in F2 / R2C6: got '1843-12-21'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Warning message:</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Expecting date in F2 / R2C6: got '1843-12-21'</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># this DOB will be converted to NA</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>CustomerAddress <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Task 1/KPMG_VI_New_raw_data_update_final.xlsx"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">sheet =</span> <span class="st">"CustomerAddress"</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>Transactions <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Task 1/KPMG_VI_New_raw_data_update_final.xlsx"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">sheet =</span> <span class="st">"Transactions"</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Task 1/KPMG_VI_New_raw_data_update_final.xlsx"</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">sheet =</span> <span class="st">"NewCustomerList"</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...17`
• `` -&gt; `...18`
• `` -&gt; `...19`
• `` -&gt; `...20`
• `` -&gt; `...21`</code></pre>
</div>
</div>
</section>
<section id="data-at-first-glance" class="level2">
<h2 class="anchored" data-anchor-id="data-at-first-glance">Data at first glance</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(CustomerDemographic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  customer_id first_name last_name gender past_3_years_bike_related_purchases
  &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;                                &lt;dbl&gt;
1 34          Jephthah   Bachmann  U                                       59
2 66          Anselm     Gawne     Male                                    46
3 1888        Sibyl      Scholtz   Female                                  67
4 3435        Stevena    Allcock   Female                                  80
5 2858        Benedicto  Radki     Male                                     4
6 422         Vito       Norker    Male                                    78
# ℹ 8 more variables: DOB &lt;dttm&gt;, job_title &lt;chr&gt;, job_industry_category &lt;chr&gt;,
#   wealth_segment &lt;chr&gt;, deceased_indicator &lt;chr&gt;, default &lt;chr&gt;,
#   owns_car &lt;chr&gt;, tenure &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(CustomerAddress)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  customer_id address             postcode state      country property_valuation
        &lt;dbl&gt; &lt;chr&gt;                  &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;                &lt;dbl&gt;
1           1 060 Morning Avenue      2016 New South… Austra…                 10
2           2 6 Meadow Vale Court     2153 New South… Austra…                 10
3           4 0 Holy Cross Court      4211 QLD        Austra…                  9
4           5 17979 Del Mar Point     2448 New South… Austra…                  4
5           6 9 Oakridge Court        3216 VIC        Austra…                  9
6           7 4 Delaware Trail        2210 New South… Austra…                  9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Transactions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  transaction_id product_id customer_id transaction_date    online_order
           &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt; &lt;dttm&gt;              &lt;lgl&gt;       
1              1          2        2950 2017-02-25 00:00:00 FALSE       
2              2          3        3120 2017-05-21 00:00:00 TRUE        
3              3         37         402 2017-10-16 00:00:00 FALSE       
4              4         88        3135 2017-08-31 00:00:00 FALSE       
5              5         78         787 2017-10-01 00:00:00 TRUE        
6              6         25        2339 2017-03-08 00:00:00 TRUE        
# ℹ 8 more variables: order_status &lt;chr&gt;, brand &lt;chr&gt;, product_line &lt;chr&gt;,
#   product_class &lt;chr&gt;, product_size &lt;chr&gt;, list_price &lt;dbl&gt;,
#   standard_cost &lt;dbl&gt;, product_first_sold_date &lt;dttm&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(NewCustomerList)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 23
  first_name last_name gender past_3_years_bike_related_purcha…¹ DOB   job_title
  &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;                              &lt;chr&gt; &lt;chr&gt;    
1 Chickie    Brister   Male   86                                 1957… General …
2 Morly      Genery    Male   69                                 1970… Structur…
3 Ardelis    Forrester Female 10                                 27269 Senior C…
4 Lucine     Stutt     Female 64                                 1979… Account …
5 Melinda    Hadlee    Female 34                                 1965… Financia…
6 Druci      Brandli   Female 39                                 1951… Assistan…
# ℹ abbreviated name: ¹​past_3_years_bike_related_purchases
# ℹ 17 more variables: job_industry_category &lt;chr&gt;, wealth_segment &lt;chr&gt;,
#   deceased_indicator &lt;chr&gt;, owns_car &lt;chr&gt;, tenure &lt;dbl&gt;, address &lt;chr&gt;,
#   postcode &lt;chr&gt;, state &lt;chr&gt;, country &lt;chr&gt;, property_valuation &lt;chr&gt;,
#   ...17 &lt;dbl&gt;, ...18 &lt;dbl&gt;, ...19 &lt;dbl&gt;, ...20 &lt;dbl&gt;, ...21 &lt;dbl&gt;,
#   Rank &lt;dbl&gt;, Value &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the number of rows and columns for each data frame</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"CustomerDemographic dimensions: "</span>, <span class="fu">dim</span>(CustomerDemographic), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CustomerDemographic dimensions:  4000 13 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"CustomerAddress dimensions: "</span>, <span class="fu">dim</span>(CustomerAddress), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CustomerAddress dimensions:  3999 6 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Transactions dimensions: "</span>, <span class="fu">dim</span>(Transactions), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Transactions dimensions:  20000 13 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"NewCustomerList dimensions: "</span>, <span class="fu">dim</span>(NewCustomerList), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NewCustomerList dimensions:  1000 23 </code></pre>
</div>
</div>
</section>
<section id="clean-customerdemographic" class="level2">
<h2 class="anchored" data-anchor-id="clean-customerdemographic">Clean CustomerDemographic</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># checking each column of CustomerDemographic for null values</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a function to count nulls in a column</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>count_nulls_in_column <span class="ot">&lt;-</span> <span class="cf">function</span>(column) {</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(column))</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a function to apply count_nulls_in_column to each column</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>count_nulls <span class="ot">&lt;-</span> <span class="cf">function</span>(df) {</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map_int</span>(df, count_nulls_in_column)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace 'your_tibble' with the actual name of your tibble</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the function to count nulls</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="fu">count_nulls</span>(CustomerDemographic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        customer_id                          first_name 
                                  0                                   0 
                          last_name                              gender 
                                125                                   0 
past_3_years_bike_related_purchases                                 DOB 
                                  0                                  88 
                          job_title               job_industry_category 
                                506                                   0 
                     wealth_segment                  deceased_indicator 
                                  0                                   0 
                            default                            owns_car 
                                240                                   0 
                             tenure 
                                 87 </code></pre>
</div>
</div>
<p>last_name, job_title, default, tenure, DOB are columns with null values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CustomerDemographic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [4,000 × 13] (S3: tbl_df/tbl/data.frame)
 $ customer_id                        : chr [1:4000] "34" "66" "1888" "3435" ...
 $ first_name                         : chr [1:4000] "Jephthah" "Anselm" "Sibyl" "Stevena" ...
 $ last_name                          : chr [1:4000] "Bachmann" "Gawne" "Scholtz" "Allcock" ...
 $ gender                             : chr [1:4000] "U" "Male" "Female" "Female" ...
 $ past_3_years_bike_related_purchases: num [1:4000] 59 46 67 80 4 78 16 22 24 58 ...
 $ DOB                                : POSIXct[1:4000], format: NA "2002-03-11" ...
 $ job_title                          : chr [1:4000] "Legal Assistant" "Account Executive" "Food Chemist" "Senior Editor" ...
 $ job_industry_category              : chr [1:4000] "IT" "Argiculture" "Health" "n/a" ...
 $ wealth_segment                     : chr [1:4000] "Affluent Customer" "High Net Worth" "Mass Customer" "Affluent Customer" ...
 $ deceased_indicator                 : chr [1:4000] "N" "N" "N" "N" ...
 $ default                            : chr [1:4000] NA "ï½ï½¨(Â´âï½â©" "NULL" "ÅâÂ´â°ËÃÂ¨ËÃâââ" ...
 $ owns_car                           : chr [1:4000] "No" "No" "Yes" "No" ...
 $ tenure                             : num [1:4000] 20 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>All data types are correct.</p>
<section id="dob" class="level3">
<h3 class="anchored" data-anchor-id="dob">DOB</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove customer whose year of birth is 1843 as this is obviously an error</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  CustomerDemographic <span class="sc">|&gt;</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(customer_id <span class="sc">!=</span> <span class="dv">34</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>DOB column has been cleaned.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  CustomerDemographic <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DOB =</span> <span class="fu">as.Date</span>(CustomerDemographic<span class="sc">$</span>DOB))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="customer_id" class="level3">
<h3 class="anchored" data-anchor-id="customer_id">customer_id</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check if customer_id is unique</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>customer_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3999</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"CustomerDemographic dimensions: "</span>, <span class="fu">dim</span>(CustomerDemographic), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CustomerDemographic dimensions:  3999 13 </code></pre>
</div>
</div>
<p>Total rows of the table is 3999 and number of unique values in customer_id is also 3999.</p>
<p>We should also check if customer_id from CustomerDemographic, CustomerAddress, and Transactions tables contain the same ids.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show the ids in CustomerAddress that are not in CustomerDemographic</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>CustomerAddress<span class="sc">$</span>customer_id[<span class="sc">!</span>(CustomerAddress<span class="sc">$</span>customer_id <span class="sc">%in%</span> CustomerDemographic<span class="sc">$</span>customer_id)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   34 4001 4002 4003</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Transactions<span class="sc">$</span>customer_id[<span class="sc">!</span>(Transactions<span class="sc">$</span>customer_id <span class="sc">%in%</span> CustomerDemographic<span class="sc">$</span>customer_id)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   34 5034</code></pre>
</div>
</div>
<p>Additional customer_ids in the Transactions table and Customer Address table but not in CustomerDemographic.</p>
<p>34 753 3790 4001 4002 4003 5034</p>
<p>We decide that only customers in the CustomerDemographic table will used for training.</p>
</section>
<section id="gender" class="level3">
<h3 class="anchored" data-anchor-id="gender">gender</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Male"   "Female" "M"      "Femal"  "F"      "U"     </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> CustomerDemographic  <span class="sc">|&gt;</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">case_when</span>(</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    gender <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"M"</span>) <span class="sc">~</span> <span class="st">"M"</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    gender <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Femal"</span>, <span class="st">"F"</span>) <span class="sc">~</span> <span class="st">"F"</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> gender  <span class="co"># Keep U as is</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the unique values after transformation</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "M" "F" "U"</code></pre>
</div>
</div>
<p>We will assume “U” as “Unknown” because these customers did not provide this information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CustomerDemographic<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   F    M    U 
2039 1873   87 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset this "U" group in case there's meaning analysis</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>Customer_U_gender <span class="ot">&lt;-</span> <span class="fu">subset</span>(CustomerDemographic, gender <span class="sc">==</span> <span class="st">"U"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="first_name-and-last_name" class="level3">
<h3 class="anchored" data-anchor-id="first_name-and-last_name">first_name and last_name</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 125 counts of customers whose last names are not provided or they don't have one</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(last_name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 125 × 13
   customer_id first_name last_name gender past_3_years_bike_relate…¹ DOB       
   &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;                       &lt;dbl&gt; &lt;date&gt;    
 1 3173        Angelo     &lt;NA&gt;      M                              55 2001-10-10
 2 2989        Mort       &lt;NA&gt;      M                              37 2000-10-25
 3 2398        Mirelle    &lt;NA&gt;      F                               6 2000-10-11
 4 3651        Baxie      &lt;NA&gt;      M                              91 1999-11-15
 5 3188        Boyd       &lt;NA&gt;      M                              94 1999-07-07
 6 3095        Joachim    &lt;NA&gt;      M                              14 1998-10-11
 7 2615        Cordelia   &lt;NA&gt;      F                              23 1998-08-13
 8 2101        Maryann    &lt;NA&gt;      F                              71 1998-03-08
 9 2189        Thedric    &lt;NA&gt;      M                              43 1998-02-25
10 2835        Deloria    &lt;NA&gt;      F                              30 1997-07-01
# ℹ 115 more rows
# ℹ abbreviated name: ¹​past_3_years_bike_related_purchases
# ℹ 7 more variables: job_title &lt;chr&gt;, job_industry_category &lt;chr&gt;,
#   wealth_segment &lt;chr&gt;, deceased_indicator &lt;chr&gt;, default &lt;chr&gt;,
#   owns_car &lt;chr&gt;, tenure &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Leave as is for now (no removal or imputation).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check and remove leading/trailing spaces from first_name and last_name</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> CustomerDemographic <span class="sc">|&gt;</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">first_name =</span> <span class="fu">trimws</span>(first_name),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_name =</span> <span class="fu">trimws</span>(last_name)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="past_3_years_bike_related_purchases" class="level3">
<h3 class="anchored" data-anchor-id="past_3_years_bike_related_purchases">past_3_years_bike_related_purchases</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CustomerDemographic, <span class="fu">aes</span>(past_3_years_bike_related_purchases)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="data-quality-assessment_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CustomerDemographic<span class="sc">$</span>past_3_years_bike_related_purchases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   24.00   48.00   48.89   73.00   99.00 </code></pre>
</div>
</div>
<p>Distribution of this column looks reasonable.</p>
</section>
<section id="job_title" class="level3">
<h3 class="anchored" data-anchor-id="job_title">job_title</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>job_title)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "Account Executive"                   
  [2] "Food Chemist"                        
  [3] "Senior Editor"                       
  [4] "Recruiting Manager"                  
  [5] NA                                    
  [6] "Geologist IV"                        
  [7] "Internal Auditor"                    
  [8] "Web Designer IV"                     
  [9] "Assistant Professor"                 
 [10] "Administrative Assistant IV"         
 [11] "Desktop Support Technician"          
 [12] "Operator"                            
 [13] "Help Desk Technician"                
 [14] "Business Systems Development Analyst"
 [15] "Data Coordiator"                     
 [16] "Computer Systems Analyst I"          
 [17] "Associate Professor"                 
 [18] "Statistician II"                     
 [19] "Actuary"                             
 [20] "Human Resources Assistant I"         
 [21] "Clinical Specialist"                 
 [22] "Assistant Media Planner"             
 [23] "Technical Writer"                    
 [24] "Chemical Engineer"                   
 [25] "Geological Engineer"                 
 [26] "VP Quality Control"                  
 [27] "Product Engineer"                    
 [28] "Budget/Accounting Analyst IV"        
 [29] "Software Engineer II"                
 [30] "Senior Financial Analyst"            
 [31] "Environmental Tech"                  
 [32] "Marketing Assistant"                 
 [33] "Professor"                           
 [34] "Nurse Practicioner"                  
 [35] "Librarian"                           
 [36] "Computer Systems Analyst II"         
 [37] "Compensation Analyst"                
 [38] "Dental Hygienist"                    
 [39] "Marketing Manager"                   
 [40] "Analyst Programmer"                  
 [41] "Electrical Engineer"                 
 [42] "Assistant Manager"                   
 [43] "Structural Analysis Engineer"        
 [44] "Information Systems Manager"         
 [45] "Staff Accountant III"                
 [46] "VP Product Management"               
 [47] "VP Sales"                            
 [48] "Junior Executive"                    
 [49] "Health Coach II"                     
 [50] "Pharmacist"                          
 [51] "Accounting Assistant III"            
 [52] "General Manager"                     
 [53] "Web Developer III"                   
 [54] "Nurse"                               
 [55] "Physical Therapy Assistant"          
 [56] "Human Resources Assistant III"       
 [57] "Accounting Assistant I"              
 [58] "Human Resources Manager"             
 [59] "Programmer Analyst II"               
 [60] "GIS Technical Architect"             
 [61] "Accountant III"                      
 [62] "Registered Nurse"                    
 [63] "Speech Pathologist"                  
 [64] "Senior Cost Accountant"              
 [65] "Administrative Officer"              
 [66] "Analog Circuit Design manager"       
 [67] "Nuclear Power Engineer"              
 [68] "Office Assistant I"                  
 [69] "Sales Associate"                     
 [70] "Senior Developer"                    
 [71] "Programmer II"                       
 [72] "Project Manager"                     
 [73] "Design Engineer"                     
 [74] "Automation Specialist I"             
 [75] "Structural Engineer"                 
 [76] "Biostatistician I"                   
 [77] "Environmental Specialist"            
 [78] "Help Desk Operator"                  
 [79] "Teacher"                             
 [80] "Financial Advisor"                   
 [81] "Staff Scientist"                     
 [82] "Quality Control Specialist"          
 [83] "Civil Engineer"                      
 [84] "Software Engineer IV"                
 [85] "Sales Representative"                
 [86] "Chief Design Engineer"               
 [87] "Account Representative IV"           
 [88] "Mechanical Systems Engineer"         
 [89] "Financial Analyst"                   
 [90] "Community Outreach Specialist"       
 [91] "Tax Accountant"                      
 [92] "Executive Secretary"                 
 [93] "Research Nurse"                      
 [94] "Statistician I"                      
 [95] "Engineer IV"                         
 [96] "Account Coordinator"                 
 [97] "Staff Accountant IV"                 
 [98] "Geologist II"                        
 [99] "Account Representative III"          
[100] "Budget/Accounting Analyst III"       
[101] "Quality Engineer"                    
[102] "Senior Sales Associate"              
[103] "Web Developer IV"                    
[104] "VP Accounting"                       
[105] "Account Representative I"            
[106] "Database Administrator III"          
[107] "Administrative Assistant II"         
[108] "Software Test Engineer IV"           
[109] "Occupational Therapist"              
[110] "Safety Technician II"                
[111] "Administrative Assistant III"        
[112] "Editor"                              
[113] "Cost Accountant"                     
[114] "Budget/Accounting Analyst I"         
[115] "Software Test Engineer III"          
[116] "Office Assistant III"                
[117] "Systems Administrator IV"            
[118] "Office Assistant II"                 
[119] "Geologist III"                       
[120] "Media Manager III"                   
[121] "Legal Assistant"                     
[122] "Software Consultant"                 
[123] "Social Worker"                       
[124] "Safety Technician III"               
[125] "Graphic Designer"                    
[126] "Web Designer III"                    
[127] "Web Designer I"                      
[128] "Accountant II"                       
[129] "Database Administrator IV"           
[130] "Programmer Analyst I"                
[131] "Research Assistant I"                
[132] "Software Engineer I"                 
[133] "Director of Sales"                   
[134] "Automation Specialist II"            
[135] "Automation Specialist III"           
[136] "Geologist I"                         
[137] "Database Administrator I"            
[138] "Web Developer I"                     
[139] "Recruiter"                           
[140] "Accounting Assistant II"             
[141] "Payment Adjustment Coordinator"      
[142] "Research Associate"                  
[143] "Paralegal"                           
[144] "Software Engineer III"               
[145] "Programmer IV"                       
[146] "Accountant I"                        
[147] "Human Resources Assistant IV"        
[148] "Computer Systems Analyst III"        
[149] "Senior Quality Engineer"             
[150] "Office Assistant IV"                 
[151] "Automation Specialist IV"            
[152] "Programmer Analyst III"              
[153] "Research Assistant II"               
[154] "Software Test Engineer II"           
[155] "VP Marketing"                        
[156] "Computer Systems Analyst IV"         
[157] "Biostatistician IV"                  
[158] "Accounting Assistant IV"             
[159] "Human Resources Assistant II"        
[160] "Biostatistician III"                 
[161] "Developer II"                        
[162] "Safety Technician I"                 
[163] "Developer III"                       
[164] "Media Manager I"                     
[165] "Accountant IV"                       
[166] "Software Test Engineer I"            
[167] "Staff Accountant I"                  
[168] "Media Manager IV"                    
[169] "Web Developer II"                    
[170] "Statistician IV"                     
[171] "Biostatistician II"                  
[172] "Engineer I"                          
[173] "Research Assistant IV"               
[174] "Engineer II"                         
[175] "Programmer III"                      
[176] "Programmer Analyst IV"               
[177] "Staff Accountant II"                 
[178] "Statistician III"                    
[179] "Systems Administrator I"             
[180] "Systems Administrator II"            
[181] "Web Designer II"                     
[182] "Media Manager II"                    
[183] "Systems Administrator III"           
[184] "Health Coach IV"                     
[185] "Account Representative II"           
[186] "Research Assistant III"              
[187] "Engineer III"                        
[188] "Developer IV"                        
[189] "Safety Technician IV"                
[190] "Database Administrator II"           
[191] "Administrative Assistant I"          
[192] "Budget/Accounting Analyst II"        
[193] "Health Coach I"                      
[194] "Health Coach III"                    
[195] "Programmer I"                        
[196] "Developer I"                         </code></pre>
</div>
</div>
</section>
<section id="job_industry_category" class="level3">
<h3 class="anchored" data-anchor-id="job_industry_category">job_industry_category</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>job_industry_category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Argiculture"        "Health"             "n/a"               
 [4] "Manufacturing"      "Retail"             "Telecommunications"
 [7] "IT"                 "Financial Services" "Entertainment"     
[10] "Property"          </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># change "n/a" to NA values</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> CustomerDemographic <span class="sc">|&gt;</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">job_industry_category =</span> <span class="fu">na_if</span>(job_industry_category, <span class="st">"n/a"</span>))</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>job_industry_category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Argiculture"        "Health"             NA                  
 [4] "Manufacturing"      "Retail"             "Telecommunications"
 [7] "IT"                 "Financial Services" "Entertainment"     
[10] "Property"          </code></pre>
</div>
</div>
</section>
<section id="wealth_segment" class="level3">
<h3 class="anchored" data-anchor-id="wealth_segment">wealth_segment</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>wealth_segment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "High Net Worth"    "Mass Customer"     "Affluent Customer"</code></pre>
</div>
</div>
</section>
<section id="deceased_indicator" class="level3">
<h3 class="anchored" data-anchor-id="deceased_indicator">deceased_indicator</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CustomerDemographic<span class="sc">$</span>deceased_indicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   N    Y 
3997    2 </code></pre>
</div>
</div>
<p>Deceased customers serve no purpose to analysis because the new targeted customers are obviously alive. Thus, the deceased customers will be removed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove deceased customers</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> <span class="fu">filter</span>(CustomerDemographic, deceased_indicator <span class="sc">==</span> <span class="st">"N"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="co"># remove deceased_indicator column</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> <span class="fu">select</span>(CustomerDemographic, <span class="sc">-</span>deceased_indicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>dlookr<span class="sc">::</span><span class="fu">diagnose</span>(CustomerDemographic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 6
   variables        types missing_count missing_percent unique_count unique_rate
   &lt;chr&gt;            &lt;chr&gt;         &lt;int&gt;           &lt;dbl&gt;        &lt;int&gt;       &lt;dbl&gt;
 1 customer_id      char…             0            0            3997    1       
 2 first_name       char…             0            0            3138    0.785   
 3 last_name        char…           125            3.13         3723    0.931   
 4 gender           char…             0            0               3    0.000751
 5 past_3_years_bi… nume…             0            0             100    0.0250  
 6 DOB              Date             87            2.18         3446    0.862   
 7 job_title        char…           506           12.7           196    0.0490  
 8 job_industry_ca… char…           656           16.4            10    0.00250 
 9 wealth_segment   char…             0            0               3    0.000751
10 default          char…           239            5.98           93    0.0233  
11 owns_car         char…             0            0               2    0.000500
12 tenure           nume…            87            2.18           23    0.00575 </code></pre>
</div>
</div>
</section>
<section id="default" class="level3">
<h3 class="anchored" data-anchor-id="default">default</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(CustomerDemographic<span class="sc">$</span>default,<span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ï½ï½¨(Â´âï½â©"                             
 [2] "NULL"                                      
 [3] "ÅâÂ´â°ËÃÂ¨ËÃâââ"                           
 [4] "testâ&nbsp;testâ«"                              
 [5] "ðµ ð ð ð"                                  
 [6] "ï½ï½¨(Â´âï½â©"                             
 [7] NA                                          
 [8] "-0.5"                                      
 [9] "ÅâÂ´â°ËÃÂ¨ËÃâââ"                           
[10] "â©testâ©"                                  
[11] "â°â´âµ"                                    
[12] "â°â´âµâââ"                                 
[13] "â¦testâ§"                                  
[14] "0/0"                                       
[15] "nil"                                       
[16] "ð©ð½"                                      
[17] "../../../../../../../../../../../etc/hosts"
[18] "&lt;img src=x onerror=alert('hi') /&gt;"         
[19] "ð¾ ð ð ð ð ð ð ð"                          
[20] "&lt;&gt;?:\"{}|_+"                               
[21] "â¦testâ§"                                  
[22] "`ââ¬â¹âºï¬ï¬â¡Â°Â·ââÂ±"                    
[23] "â"                                         
[24] "ì¬íê³¼íì ì´íì°êµ¬ì"                        
[25] "â©testâ©"                                  </code></pre>
</div>
</div>
<p>Seems to be some corrupted text metadata. We will remove this column also.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>CustomerDemographic <span class="ot">&lt;-</span> <span class="fu">select</span>(CustomerDemographic, <span class="sc">!</span>default)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="owns_car" class="level3">
<h3 class="anchored" data-anchor-id="owns_car">owns_car</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CustomerDemographic<span class="sc">$</span>owns_car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  No  Yes 
1975 2022 </code></pre>
</div>
</div>
</section>
<section id="tenure" class="level3">
<h3 class="anchored" data-anchor-id="tenure">tenure</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>tenure))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CustomerDemographic<span class="sc">$</span>tenure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   1.00    6.00   11.00   10.66   15.00   22.00      87 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CustomerDemographic, <span class="fu">aes</span>(tenure)) <span class="sc">+</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 87 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="data-quality-assessment_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CustomerDemographic, <span class="fu">aes</span>(tenure)) <span class="sc">+</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 87 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="data-quality-assessment_files/figure-html/unnamed-chunk-30-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We will assume that tenure represents the number of years each customer has been a customer of the company.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count_nulls</span>(CustomerDemographic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        customer_id                          first_name 
                                  0                                   0 
                          last_name                              gender 
                                125                                   0 
past_3_years_bike_related_purchases                                 DOB 
                                  0                                  87 
                          job_title               job_industry_category 
                                506                                 656 
                     wealth_segment                            owns_car 
                                  0                                   0 
                             tenure 
                                 87 </code></pre>
</div>
</div>
</section>
</section>
<section id="clean-customeraddress" class="level2">
<h2 class="anchored" data-anchor-id="clean-customeraddress">Clean CustomerAddress</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CustomerAddress)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [3,999 × 6] (S3: tbl_df/tbl/data.frame)
 $ customer_id       : num [1:3999] 1 2 4 5 6 7 8 9 11 12 ...
 $ address           : chr [1:3999] "060 Morning Avenue" "6 Meadow Vale Court" "0 Holy Cross Court" "17979 Del Mar Point" ...
 $ postcode          : num [1:3999] 2016 2153 4211 2448 3216 ...
 $ state             : chr [1:3999] "New South Wales" "New South Wales" "QLD" "New South Wales" ...
 $ country           : chr [1:3999] "Australia" "Australia" "Australia" "Australia" ...
 $ property_valuation: num [1:3999] 10 10 9 4 9 9 4 12 8 4 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>CustomerAddress<span class="sc">$</span>customer_id <span class="ot">&lt;-</span> <span class="fu">as.character</span>(CustomerAddress<span class="sc">$</span>customer_id)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>CustomerAddress<span class="sc">$</span>postcode <span class="ot">&lt;-</span> <span class="fu">as.character</span>(CustomerAddress<span class="sc">$</span>postcode)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count_nulls</span>(CustomerAddress)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       customer_id            address           postcode              state 
                 0                  0                  0                  0 
           country property_valuation 
                 0                  0 </code></pre>
</div>
</div>
<section id="customer_id-1" class="level3">
<h3 class="anchored" data-anchor-id="customer_id-1">customer_id</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove customers with ids 34  753 3790 4001 4002 4003 for CustomerAddress</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>CustomerAddress <span class="ot">&lt;-</span> CustomerAddress <span class="sc">|&gt;</span> </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(customer_id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"34"</span>, <span class="st">"753"</span>, <span class="st">"3790"</span>, <span class="st">"4001"</span>, <span class="st">"4002"</span>, <span class="st">"4003"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="address" class="level3">
<h3 class="anchored" data-anchor-id="address">address</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(CustomerAddress<span class="sc">$</span>address, <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "060 Morning Avenue"      "6 Meadow Vale Court"    
 [3] "0 Holy Cross Court"      "17979 Del Mar Point"    
 [5] "9 Oakridge Court"        "4 Delaware Trail"       
 [7] "49 Londonderry Lane"     "97736 7th Trail"        
 [9] "93405 Ludington Park"    "44339 Golden Leaf Alley"
[11] "2 Sutherland Street"     "9 Mcbride Trail"        
[13] "9861 New Castle Avenue"  "52 Moland Street"       
[15] "82391 Kensington Lane"  </code></pre>
</div>
</div>
</section>
<section id="postcode" class="level3">
<h3 class="anchored" data-anchor-id="postcode">postcode</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(CustomerAddress<span class="sc">$</span>postcode, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "2016" "2153" "4211" "2448" "3216" "2210" "2650" "2023" "3044" "4557"</code></pre>
</div>
</div>
</section>
<section id="state" class="level3">
<h3 class="anchored" data-anchor-id="state">state</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(CustomerAddress<span class="sc">$</span>state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "New South Wales" "QLD"             "VIC"             "NSW"            
[5] "Victoria"       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>CustomerAddress <span class="ot">&lt;-</span> CustomerAddress <span class="sc">|&gt;</span> </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">case_when</span>(</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>    state <span class="sc">==</span> <span class="st">"New South Wales"</span> <span class="sc">~</span> <span class="st">"NSW"</span>,</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>    state <span class="sc">==</span> <span class="st">"Queensland"</span> <span class="sc">~</span> <span class="st">"QLD"</span>,</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>    state <span class="sc">==</span> <span class="st">"Victoria"</span> <span class="sc">~</span> <span class="st">"VIC"</span>,</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> state  <span class="co"># Keep other values unchanged</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="country" class="level3">
<h3 class="anchored" data-anchor-id="country">country</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(CustomerAddress<span class="sc">$</span>country)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Australia"</code></pre>
</div>
</div>
</section>
<section id="property_valuation" class="level3">
<h3 class="anchored" data-anchor-id="property_valuation">property_valuation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CustomerAddress<span class="sc">$</span>property_valuation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   6.000   8.000   7.516  10.000  12.000 </code></pre>
</div>
</div>
</section>
</section>
<section id="clean-transactions" class="level2">
<h2 class="anchored" data-anchor-id="clean-transactions">Clean Transactions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Transactions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [20,000 × 13] (S3: tbl_df/tbl/data.frame)
 $ transaction_id         : num [1:20000] 1 2 3 4 5 6 7 8 9 10 ...
 $ product_id             : num [1:20000] 2 3 37 88 78 25 22 15 67 12 ...
 $ customer_id            : num [1:20000] 2950 3120 402 3135 787 ...
 $ transaction_date       : POSIXct[1:20000], format: "2017-02-25" "2017-05-21" ...
 $ online_order           : logi [1:20000] FALSE TRUE FALSE FALSE TRUE TRUE ...
 $ order_status           : chr [1:20000] "Approved" "Approved" "Approved" "Approved" ...
 $ brand                  : chr [1:20000] "Solex" "Trek Bicycles" "OHM Cycles" "Norco Bicycles" ...
 $ product_line           : chr [1:20000] "Standard" "Standard" "Standard" "Standard" ...
 $ product_class          : chr [1:20000] "medium" "medium" "low" "medium" ...
 $ product_size           : chr [1:20000] "medium" "large" "medium" "medium" ...
 $ list_price             : num [1:20000] 71.5 2091.5 1793.4 1198.5 1765.3 ...
 $ standard_cost          : num [1:20000] 53.6 388.9 248.8 381.1 709.5 ...
 $ product_first_sold_date: POSIXct[1:20000], format: "2012-12-02" "2014-03-03" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>Transactions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20,000 × 13
   transaction_id product_id customer_id transaction_date    online_order
            &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt; &lt;dttm&gt;              &lt;lgl&gt;       
 1              1          2        2950 2017-02-25 00:00:00 FALSE       
 2              2          3        3120 2017-05-21 00:00:00 TRUE        
 3              3         37         402 2017-10-16 00:00:00 FALSE       
 4              4         88        3135 2017-08-31 00:00:00 FALSE       
 5              5         78         787 2017-10-01 00:00:00 TRUE        
 6              6         25        2339 2017-03-08 00:00:00 TRUE        
 7              7         22        1542 2017-04-21 00:00:00 TRUE        
 8              8         15        2459 2017-07-15 00:00:00 FALSE       
 9              9         67        1305 2017-08-10 00:00:00 FALSE       
10             10         12        3262 2017-08-30 00:00:00 TRUE        
# ℹ 19,990 more rows
# ℹ 8 more variables: order_status &lt;chr&gt;, brand &lt;chr&gt;, product_line &lt;chr&gt;,
#   product_class &lt;chr&gt;, product_size &lt;chr&gt;, list_price &lt;dbl&gt;,
#   standard_cost &lt;dbl&gt;, product_first_sold_date &lt;dttm&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>Transactions <span class="ot">&lt;-</span> Transactions <span class="sc">|&gt;</span> </span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">transaction_id =</span> <span class="fu">as.character</span>(transaction_id),</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">customer_id =</span> <span class="fu">as.character</span>(customer_id),</span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">product_id =</span> <span class="fu">as.character</span>(product_id),</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">product_first_sold_date =</span> <span class="fu">as.Date</span>(<span class="fu">as.POSIXct</span>(<span class="st">"1899-12-30"</span>)) <span class="sc">+</span> </span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>      lubridate<span class="sc">::</span><span class="fu">days</span>(product_first_sold_date),</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">transaction_date =</span> <span class="fu">as.Date</span>(transaction_date)</span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count_nulls</span>(Transactions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         transaction_id              product_id             customer_id 
                      0                       0                       0 
       transaction_date            online_order            order_status 
                      0                     360                       0 
                  brand            product_line           product_class 
                    197                     197                     197 
           product_size              list_price           standard_cost 
                    197                       0                     197 
product_first_sold_date 
                    197 </code></pre>
</div>
</div>
<p>brand, product_size, product_size, product_line, product_class, standard_cost are missing with the same amount of values. Potentially, 197 transaction observations are missing this product info.</p>
<p>We will remove these transactions from training and subset it for further analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>Tx_missing_product_info <span class="ot">&lt;-</span> Transactions <span class="sc">|&gt;</span> </span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">is.na</span>(brand) <span class="sc">&amp;</span> <span class="fu">is.na</span>(product_size) <span class="sc">&amp;</span> <span class="fu">is.na</span>(product_line) <span class="sc">&amp;</span></span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">is.na</span>(product_class) <span class="sc">&amp;</span> <span class="fu">is.na</span>(standard_cost)</span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>Tx_missing_product_info</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 197 × 13
   transaction_id product_id customer_id transaction_date online_order
   &lt;chr&gt;          &lt;chr&gt;      &lt;chr&gt;       &lt;date&gt;           &lt;lgl&gt;       
 1 137            0          431         2017-09-23       FALSE       
 2 160            0          3300        2017-08-27       FALSE       
 3 367            0          1614        2017-03-10       FALSE       
 4 407            0          2559        2017-06-14       TRUE        
 5 677            0          2609        2017-07-02       FALSE       
 6 781            0          897         2017-05-10       TRUE        
 7 1004           0          2254        2017-05-16       FALSE       
 8 1131           0          2163        2017-03-09       FALSE       
 9 1197           0          2234        2017-04-04       FALSE       
10 1283           0          397         2017-08-09       FALSE       
# ℹ 187 more rows
# ℹ 8 more variables: order_status &lt;chr&gt;, brand &lt;chr&gt;, product_line &lt;chr&gt;,
#   product_class &lt;chr&gt;, product_size &lt;chr&gt;, list_price &lt;dbl&gt;,
#   standard_cost &lt;dbl&gt;, product_first_sold_date &lt;date&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Tx_missing_product_info<span class="sc">$</span>product_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "0"</code></pre>
</div>
</div>
<p>There appears to be missing product info only for product id 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># # remove transactions missing product info</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Transactions &lt;- Transactions |&gt; </span></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a><span class="co">#     filter(</span></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a><span class="co">#     !(is.na(brand) &amp; is.na(product_size) &amp; is.na(product_line) &amp;</span></span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a><span class="co">#     is.na(product_class) &amp; is.na(standard_cost))</span></span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   )</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="transaction_date" class="level3">
<h3 class="anchored" data-anchor-id="transaction_date">transaction_date</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(<span class="fu">format</span>(Transactions<span class="sc">$</span>transaction_date, <span class="st">"%Y-%m-%d"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2017-01-01"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">format</span>(Transactions<span class="sc">$</span>transaction_date, <span class="st">"%Y-%m-%d"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2017-12-30"</code></pre>
</div>
</div>
<p>a year worth of transaction data.</p>
</section>
<section id="transaction_id" class="level3">
<h3 class="anchored" data-anchor-id="transaction_id">transaction_id</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(Transactions<span class="sc">$</span>transaction_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(Transactions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20000</code></pre>
</div>
</div>
</section>
<section id="product_id" class="level3">
<h3 class="anchored" data-anchor-id="product_id">product_id</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(Transactions<span class="sc">$</span>product_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 101</code></pre>
</div>
</div>
<p>101 products.</p>
</section>
<section id="customer_id-2" class="level3">
<h3 class="anchored" data-anchor-id="customer_id-2">customer_id</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove ids 753, 34, 5034</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="co"># note that this will remove more than three transactions </span></span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a><span class="co"># because customer ids are not unique</span></span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a>Transactions <span class="ot">&lt;-</span> Transactions <span class="sc">|&gt;</span> </span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(customer_id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"753"</span>, <span class="st">"34"</span>, <span class="st">"5034"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(Transactions<span class="sc">$</span>customer_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3491</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(CustomerDemographic<span class="sc">$</span>customer_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3997</code></pre>
</div>
</div>
<p>within the past year, 506 customers did not make a transaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="co"># identify these customers by id and subset</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>Customer_0tx_past_yr <span class="ot">&lt;-</span> CustomerDemographic <span class="sc">%&gt;%</span></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(Transactions, <span class="at">by =</span> <span class="st">"customer_id"</span>)</span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-5"><a href="#cb125-5" aria-hidden="true" tabindex="-1"></a>Customer_0tx_past_yr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 506 × 11
   customer_id first_name  last_name   gender past_3_years_bike_rel…¹ DOB       
   &lt;chr&gt;       &lt;chr&gt;       &lt;chr&gt;       &lt;chr&gt;                    &lt;dbl&gt; &lt;date&gt;    
 1 3949        Costa       Sleightholm M                           24 2001-12-19
 2 3997        Blanch      Nisuis      F                           87 2001-07-13
 3 3607        Troy        Blaydes     M                           99 2001-05-22
 4 3749        Blondelle   Swynley     F                            3 2001-04-21
 5 3616        Vale        Dagnan      M                           42 2001-04-02
 6 852         Andie       Bonney      F                           37 2000-11-04
 7 3960        Hobart      Burgan      M                            6 2000-03-16
 8 3954        Archaimbaud McAteer     M                           63 2000-02-03
 9 3850        Alexandro   McCullock   M                           55 2000-01-07
10 3675        Samuele     Heller      M                           88 1999-12-17
# ℹ 496 more rows
# ℹ abbreviated name: ¹​past_3_years_bike_related_purchases
# ℹ 5 more variables: job_title &lt;chr&gt;, job_industry_category &lt;chr&gt;,
#   wealth_segment &lt;chr&gt;, owns_car &lt;chr&gt;, tenure &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="product_first_sold_date" class="level3">
<h3 class="anchored" data-anchor-id="product_first_sold_date">product_first_sold_date</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.Date</span>(Transactions<span class="sc">$</span>product_first_sold_date))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Min.         1st Qu.          Median            Mean         3rd Qu. 
"1821009-03-21" "2390634-01-21" "2993613-03-04" "2989750-05-22" "3574592-08-28" 
           Max.            NA's 
"4056692-02-01"           "196" </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>Tx_missing_product_info <span class="sc">|&gt;</span> </span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(<span class="at">y =</span> Transactions, <span class="at">by =</span> <span class="st">"customer_id"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 13
  transaction_id product_id customer_id transaction_date online_order
  &lt;chr&gt;          &lt;chr&gt;      &lt;chr&gt;       &lt;date&gt;           &lt;lgl&gt;       
1 16935          0          34          2017-02-14       FALSE       
# ℹ 8 more variables: order_status &lt;chr&gt;, brand &lt;chr&gt;, product_line &lt;chr&gt;,
#   product_class &lt;chr&gt;, product_size &lt;chr&gt;, list_price &lt;dbl&gt;,
#   standard_cost &lt;dbl&gt;, product_first_sold_date &lt;date&gt;</code></pre>
</div>
</div>
</section>
<section id="online_order" class="level3">
<h3 class="anchored" data-anchor-id="online_order">online_order</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Transactions<span class="sc">$</span>online_order)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE  TRUE    NA</code></pre>
</div>
</div>
</section>
<section id="order_status" class="level3">
<h3 class="anchored" data-anchor-id="order_status">order_status</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Transactions<span class="sc">$</span>order_status)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Approved"  "Cancelled"</code></pre>
</div>
</div>
</section>
<section id="brand" class="level3">
<h3 class="anchored" data-anchor-id="brand">brand</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Transactions<span class="sc">$</span>brand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Solex"          "Trek Bicycles"  "OHM Cycles"     "Norco Bicycles"
[5] "Giant Bicycles" "WeareA2B"       NA              </code></pre>
</div>
</div>
</section>
<section id="product_line" class="level3">
<h3 class="anchored" data-anchor-id="product_line">product_line</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Transactions<span class="sc">$</span>product_line)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Standard" "Road"     "Mountain" "Touring"  NA        </code></pre>
</div>
</div>
</section>
<section id="product_class" class="level3">
<h3 class="anchored" data-anchor-id="product_class">product_class</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Transactions<span class="sc">$</span>product_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "medium" "low"    "high"   NA      </code></pre>
</div>
</div>
</section>
<section id="product_size" class="level3">
<h3 class="anchored" data-anchor-id="product_size">product_size</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Transactions<span class="sc">$</span>product_size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "medium" "large"  "small"  NA      </code></pre>
</div>
</div>
</section>
<section id="product_size-1" class="level3">
<h3 class="anchored" data-anchor-id="product_size-1">product_size</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(Transactions<span class="sc">$</span>product_size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "medium" "large"  "small"  NA      </code></pre>
</div>
</div>
</section>
<section id="standard_cost" class="level3">
<h3 class="anchored" data-anchor-id="standard_cost">standard_cost</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Transactions<span class="sc">$</span>standard_cost)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   7.21  215.14  507.58  555.94  795.10 1759.85     196 </code></pre>
</div>
</div>
</section>
<section id="list_price" class="level3">
<h3 class="anchored" data-anchor-id="list_price">list_price</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Transactions<span class="sc">$</span>list_price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  12.01  575.27 1163.89 1107.61 1635.30 2091.47 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count_nulls</span>(Transactions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         transaction_id              product_id             customer_id 
                      0                       0                       0 
       transaction_date            online_order            order_status 
                      0                     360                       0 
                  brand            product_line           product_class 
                    196                     196                     196 
           product_size              list_price           standard_cost 
                    196                       0                     196 
product_first_sold_date 
                    196 </code></pre>
</div>
</div>
</section>
</section>
<section id="clean-newcustomerlist" class="level2">
<h2 class="anchored" data-anchor-id="clean-newcustomerlist">Clean NewCustomerList</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove column 17 - 23</span></span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> NewCustomerList[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">17</span><span class="sc">:</span><span class="dv">23</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(NewCustomerList)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,000 × 16] (S3: tbl_df/tbl/data.frame)
 $ first_name                         : chr [1:1000] "Chickie" "Morly" "Ardelis" "Lucine" ...
 $ last_name                          : chr [1:1000] "Brister" "Genery" "Forrester" "Stutt" ...
 $ gender                             : chr [1:1000] "Male" "Male" "Female" "Female" ...
 $ past_3_years_bike_related_purchases: chr [1:1000] "86" "69" "10" "64" ...
 $ DOB                                : chr [1:1000] "1957-07-12" "1970-03-22" "27269" "1979-01-28" ...
 $ job_title                          : chr [1:1000] "General Manager" "Structural Engineer" "Senior Cost Accountant" "Account Representative III" ...
 $ job_industry_category              : chr [1:1000] "Manufacturing" "Property" "Financial Services" "Manufacturing" ...
 $ wealth_segment                     : chr [1:1000] "Mass Customer" "Mass Customer" "Affluent Customer" "Affluent Customer" ...
 $ deceased_indicator                 : chr [1:1000] "N" "N" "N" "N" ...
 $ owns_car                           : chr [1:1000] "Yes" "No" "No" "Yes" ...
 $ tenure                             : num [1:1000] 14 16 10 5 19 22 8 10 5 17 ...
 $ address                            : chr [1:1000] "45 Shopko Center" "14 Mccormick Park" "5 Colorado Crossing" "207 Annamark Plaza" ...
 $ postcode                           : chr [1:1000] "4500" "2113" "3505" "4814" ...
 $ state                              : chr [1:1000] "QLD" "NSW" "VIC" "QLD" ...
 $ country                            : chr [1:1000] "Australia" "Australia" "Australia" "Australia" ...
 $ property_valuation                 : chr [1:1000] "6" "11" "5" "1" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count_nulls</span>(NewCustomerList)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         first_name                           last_name 
                                  0                                  29 
                             gender past_3_years_bike_related_purchases 
                                  0                                   0 
                                DOB                           job_title 
                                 17                                 106 
              job_industry_category                      wealth_segment 
                                  0                                   0 
                 deceased_indicator                            owns_car 
                                  0                                   0 
                             tenure                             address 
                                  0                                   0 
                           postcode                               state 
                                  0                                   0 
                            country                  property_valuation 
                                  0                                   0 </code></pre>
</div>
</div>
<section id="past_3_years_bike_related_purchases-1" class="level3">
<h3 class="anchored" data-anchor-id="past_3_years_bike_related_purchases-1">past_3_years_bike_related_purchases</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> NewCustomerList <span class="sc">|&gt;</span> </span>
<span id="cb156-2"><a href="#cb156-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">past_3_years_bike_related_purchases =</span> <span class="fu">as.numeric</span>(past_3_years_bike_related_purchases))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NewCustomerList<span class="sc">$</span>past_3_years_bike_related_purchases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   26.75   51.00   49.84   72.00   99.00 </code></pre>
</div>
</div>
</section>
<section id="property_valuation-1" class="level3">
<h3 class="anchored" data-anchor-id="property_valuation-1">property_valuation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> NewCustomerList <span class="sc">|&gt;</span> </span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">property_valuation =</span> <span class="fu">as.numeric</span>(property_valuation))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb160"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb160-1"><a href="#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NewCustomerList<span class="sc">$</span>property_valuation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   6.000   8.000   7.397   9.000  12.000 </code></pre>
</div>
</div>
</section>
<section id="first_name" class="level3">
<h3 class="anchored" data-anchor-id="first_name">first_name</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>first_name),<span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Chickie"   "Morly"     "Ardelis"   "Lucine"    "Melinda"   "Druci"    
 [7] "Rutledge"  "Nancie"    "Duff"      "Barthel"   "Rockwell"  "Wheeler"  
[13] "Olag"      "Melba"     "Mandie"    "Dukie"     "Marcelia"  "Winnifred"
[19] "Odilia"    "Karly"     "Teddie"    "Gaston"    "Otis"      "Tabbatha" 
[25] "Brena"    </code></pre>
</div>
</div>
</section>
<section id="last_name" class="level3">
<h3 class="anchored" data-anchor-id="last_name">last_name</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb164"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>last_name),<span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Brister"      "Genery"       "Forrester"    "Stutt"        "Hadlee"      
 [6] "Brandli"      "Hallt"        "Vian"         "Karlowicz"    "Docket"      
[11] "Matson"       "Winward"      NA             "Spellacy"     "Feares"      
[16] "Swire"        "Monkleigh"    "Beswetherick" "Quick"        "Willavize"   
[21] "Burchill"     "Dallaghan"    "Ottey"        "Averill"      "Schnitter"   </code></pre>
</div>
</div>
</section>
<section id="dob-1" class="level3">
<h3 class="anchored" data-anchor-id="dob-1">DOB</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="co"># customers that have DOBs stored as numeric text</span></span>
<span id="cb166-2"><a href="#cb166-2" aria-hidden="true" tabindex="-1"></a>NCL_subset_numericDOB <span class="ot">&lt;-</span> NewCustomerList <span class="sc">|&gt;</span> </span>
<span id="cb166-3"><a href="#cb166-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DOB =</span> <span class="fu">as.double</span>(NewCustomerList<span class="sc">$</span>DOB)) <span class="sc">|&gt;</span> </span>
<span id="cb166-4"><a href="#cb166-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(<span class="fu">is.na</span>(DOB)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `DOB = as.double(NewCustomerList$DOB)`.
Caused by warning:
! NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a>NCL_subset_numericDOB <span class="ot">&lt;-</span> NCL_subset_numericDOB <span class="sc">|&gt;</span> </span>
<span id="cb168-2"><a href="#cb168-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb168-3"><a href="#cb168-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">DOB =</span> <span class="fu">as.Date</span>(<span class="fu">as.POSIXct</span>(<span class="st">"1899-12-30"</span>) <span class="sc">+</span> </span>
<span id="cb168-4"><a href="#cb168-4" aria-hidden="true" tabindex="-1"></a>      lubridate<span class="sc">::</span><span class="fu">days</span>(DOB))</span>
<span id="cb168-5"><a href="#cb168-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb168-6"><a href="#cb168-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb168-7"><a href="#cb168-7" aria-hidden="true" tabindex="-1"></a><span class="co"># customers whose DOBs are not known</span></span>
<span id="cb168-8"><a href="#cb168-8" aria-hidden="true" tabindex="-1"></a>NCL_subset_NA_DOB <span class="ot">&lt;-</span> NewCustomerList <span class="sc">|&gt;</span> </span>
<span id="cb168-9"><a href="#cb168-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(DOB)) <span class="sc">|&gt;</span> </span>
<span id="cb168-10"><a href="#cb168-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DOB =</span> <span class="fu">as.Date</span>(DOB))</span>
<span id="cb168-11"><a href="#cb168-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb168-12"><a href="#cb168-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb168-13"><a href="#cb168-13" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> NewCustomerList <span class="sc">|&gt;</span> </span>
<span id="cb168-14"><a href="#cb168-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DOB =</span> <span class="fu">as.Date</span>(NewCustomerList<span class="sc">$</span>DOB)) <span class="sc">|&gt;</span> </span>
<span id="cb168-15"><a href="#cb168-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(DOB))</span>
<span id="cb168-16"><a href="#cb168-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb168-17"><a href="#cb168-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb168-18"><a href="#cb168-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the tables vertically</span></span>
<span id="cb168-19"><a href="#cb168-19" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(NewCustomerList, NCL_subset_numericDOB, NCL_subset_NA_DOB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="gender-1" class="level3">
<h3 class="anchored" data-anchor-id="gender-1">gender</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb169"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb169-1"><a href="#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Male"   "Female" "U"     </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb171"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb171-1"><a href="#cb171-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to make it consistent with gender column in CustomerDemographic</span></span>
<span id="cb171-2"><a href="#cb171-2" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> NewCustomerList <span class="sc">%&gt;%</span></span>
<span id="cb171-3"><a href="#cb171-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb171-4"><a href="#cb171-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender =</span> <span class="fu">case_when</span>(</span>
<span id="cb171-5"><a href="#cb171-5" aria-hidden="true" tabindex="-1"></a>      gender <span class="sc">==</span> <span class="st">"Male"</span> <span class="sc">~</span> <span class="st">"M"</span>,</span>
<span id="cb171-6"><a href="#cb171-6" aria-hidden="true" tabindex="-1"></a>      gender <span class="sc">==</span> <span class="st">"Female"</span> <span class="sc">~</span> <span class="st">"F"</span>,</span>
<span id="cb171-7"><a href="#cb171-7" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> gender  <span class="co"># Keep "U" as is</span></span>
<span id="cb171-8"><a href="#cb171-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb171-9"><a href="#cb171-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="job_title-1" class="level3">
<h3 class="anchored" data-anchor-id="job_title-1">job_title</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb172"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb172-1"><a href="#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>job_title),<span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "General Manager"              "Structural Engineer"         
 [3] "Account Representative III"   "Financial Analyst"           
 [5] "Assistant Media Planner"      "Compensation Analyst"        
 [7] "Human Resources Assistant II" "Speech Pathologist"          
 [9] "Accounting Assistant IV"      "Programmer Analyst I"        
[11] "Environmental Specialist"     "Human Resources Manager"     
[13] "VP Marketing"                 "Clinical Specialist"         
[15] NA                             "Associate Professor"         
[17] "Internal Auditor"             "Programmer I"                
[19] "Quality Engineer"             "Account Executive"           
[21] "Engineer II"                  "Nurse"                       
[23] "Librarian"                    "Paralegal"                   
[25] "Senior Quality Engineer"     </code></pre>
</div>
</div>
</section>
<section id="job_industry_category-1" class="level3">
<h3 class="anchored" data-anchor-id="job_industry_category-1">job_industry_category</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb174"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb174-1"><a href="#cb174-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>job_industry_category),<span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Manufacturing"      "Property"           "Financial Services"
 [4] "Entertainment"      "Retail"             "IT"                
 [7] "Telecommunications" "Health"             "n/a"               
[10] "Argiculture"       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb176"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb176-1"><a href="#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="co"># change "n/a" into NA value</span></span>
<span id="cb176-2"><a href="#cb176-2" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> NewCustomerList <span class="sc">%&gt;%</span></span>
<span id="cb176-3"><a href="#cb176-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb176-4"><a href="#cb176-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">job_industry_category =</span> <span class="fu">ifelse</span>(job_industry_category <span class="sc">==</span> <span class="st">"n/a"</span>, <span class="cn">NA</span>, </span>
<span id="cb176-5"><a href="#cb176-5" aria-hidden="true" tabindex="-1"></a>                                   job_industry_category)</span>
<span id="cb176-6"><a href="#cb176-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="wealth_segment-1" class="level3">
<h3 class="anchored" data-anchor-id="wealth_segment-1">wealth_segment</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb177"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb177-1"><a href="#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>wealth_segment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mass Customer"     "Affluent Customer" "High Net Worth"   </code></pre>
</div>
</div>
</section>
<section id="deceased_indicator-1" class="level3">
<h3 class="anchored" data-anchor-id="deceased_indicator-1">deceased_indicator</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb179"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb179-1"><a href="#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>deceased_indicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "N"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb181"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb181-1"><a href="#cb181-1" aria-hidden="true" tabindex="-1"></a>NewCustomerList <span class="ot">&lt;-</span> NewCustomerList <span class="sc">|&gt;</span> </span>
<span id="cb181-2"><a href="#cb181-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>deceased_indicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="owns_car-1" class="level3">
<h3 class="anchored" data-anchor-id="owns_car-1">owns_car</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb182"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb182-1"><a href="#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>owns_car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Yes" "No" </code></pre>
</div>
</div>
</section>
<section id="tenure-1" class="level3">
<h3 class="anchored" data-anchor-id="tenure-1">tenure</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb184"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb184-1"><a href="#cb184-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(NewCustomerList<span class="sc">$</span>tenure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    7.00   11.00   11.39   15.00   22.00 </code></pre>
</div>
</div>
</section>
<section id="address-1" class="level3">
<h3 class="anchored" data-anchor-id="address-1">address</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb186"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb186-1"><a href="#cb186-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>address),<span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "45 Shopko Center"      "14 Mccormick Park"     "207 Annamark Plaza"   
 [4] "115 Montana Place"     "89105 Pearson Terrace" "7 Nevada Crossing"    
 [7] "85 Carioca Point"      "717 West Drive"        "80 Scofield Junction" 
[10] "3682 Crowley Point"    "3 Golden Leaf Point"   "0484 North Avenue"    
[13] "0591 Anzinger Circle"  "39 Kedzie Pass"        "64 Granby Parkway"    
[16] "610 Swallow Street"    "1550 Russell Way"      "193 North Point"      
[19] "321 Raven Plaza"       "656 Fuller Street"     "1562 Merchant Street" 
[22] "67 Shelley Street"     "75 Cordelia Trail"     "51 Hooker Court"      
[25] "1859 Forest Circle"   </code></pre>
</div>
</div>
</section>
<section id="state-1" class="level3">
<h3 class="anchored" data-anchor-id="state-1">state</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb188"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb188-1"><a href="#cb188-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "QLD" "NSW" "VIC"</code></pre>
</div>
</div>
</section>
<section id="postcode-1" class="level3">
<h3 class="anchored" data-anchor-id="postcode-1">postcode</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb190"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb190-1"><a href="#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>postcode),<span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "4500" "2113" "4814" "2093" "4075" "2620" "2200" "4151" "4573" "3216"
[11] "2032" "2232" "4053" "2500" "4051" "2222" "2190" "2161" "2783" "4744"
[21] "4703" "4817" "2640" "4000" "4171"</code></pre>
</div>
</div>
</section>
<section id="country-1" class="level3">
<h3 class="anchored" data-anchor-id="country-1">country</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb192"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb192-1"><a href="#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(NewCustomerList<span class="sc">$</span>country)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Australia"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb194"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb194-1"><a href="#cb194-1" aria-hidden="true" tabindex="-1"></a>              <span class="co">#            first_name                           last_name </span></span>
<span id="cb194-2"><a href="#cb194-2" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                     0                                  29 </span></span>
<span id="cb194-3"><a href="#cb194-3" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                gender past_3_years_bike_related_purchases </span></span>
<span id="cb194-4"><a href="#cb194-4" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                     0                                   0 </span></span>
<span id="cb194-5"><a href="#cb194-5" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                   DOB                           job_title </span></span>
<span id="cb194-6"><a href="#cb194-6" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                    17                                 106 </span></span>
<span id="cb194-7"><a href="#cb194-7" aria-hidden="true" tabindex="-1"></a>              <span class="co"># job_industry_category                      wealth_segment </span></span>
<span id="cb194-8"><a href="#cb194-8" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                     0                                   0 </span></span>
<span id="cb194-9"><a href="#cb194-9" aria-hidden="true" tabindex="-1"></a>              <span class="co">#    deceased_indicator                            owns_car </span></span>
<span id="cb194-10"><a href="#cb194-10" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                     0                                   0 </span></span>
<span id="cb194-11"><a href="#cb194-11" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                tenure                             address </span></span>
<span id="cb194-12"><a href="#cb194-12" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                     0                                   0 </span></span>
<span id="cb194-13"><a href="#cb194-13" aria-hidden="true" tabindex="-1"></a>              <span class="co">#              postcode                               state </span></span>
<span id="cb194-14"><a href="#cb194-14" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                     0                                   0 </span></span>
<span id="cb194-15"><a href="#cb194-15" aria-hidden="true" tabindex="-1"></a>              <span class="co">#               country                  property_valuation </span></span>
<span id="cb194-16"><a href="#cb194-16" aria-hidden="true" tabindex="-1"></a>              <span class="co">#                     0                                   0 </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="export-cleansed-csv-files" class="level2">
<h2 class="anchored" data-anchor-id="export-cleansed-csv-files">Export cleansed csv files</h2>
<p>final look at the four data sets before export.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb195"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb195-1"><a href="#cb195-1" aria-hidden="true" tabindex="-1"></a>Transactions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19,980 × 13
   transaction_id product_id customer_id transaction_date online_order
   &lt;chr&gt;          &lt;chr&gt;      &lt;chr&gt;       &lt;date&gt;           &lt;lgl&gt;       
 1 1              2          2950        2017-02-25       FALSE       
 2 2              3          3120        2017-05-21       TRUE        
 3 3              37         402         2017-10-16       FALSE       
 4 4              88         3135        2017-08-31       FALSE       
 5 5              78         787         2017-10-01       TRUE        
 6 6              25         2339        2017-03-08       TRUE        
 7 7              22         1542        2017-04-21       TRUE        
 8 8              15         2459        2017-07-15       FALSE       
 9 9              67         1305        2017-08-10       FALSE       
10 10             12         3262        2017-08-30       TRUE        
# ℹ 19,970 more rows
# ℹ 8 more variables: order_status &lt;chr&gt;, brand &lt;chr&gt;, product_line &lt;chr&gt;,
#   product_class &lt;chr&gt;, product_size &lt;chr&gt;, list_price &lt;dbl&gt;,
#   standard_cost &lt;dbl&gt;, product_first_sold_date &lt;date&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb197"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb197-1"><a href="#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Transactions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [19,980 × 13] (S3: tbl_df/tbl/data.frame)
 $ transaction_id         : chr [1:19980] "1" "2" "3" "4" ...
 $ product_id             : chr [1:19980] "2" "3" "37" "88" ...
 $ customer_id            : chr [1:19980] "2950" "3120" "402" "3135" ...
 $ transaction_date       : Date[1:19980], format: "2017-02-25" "2017-05-21" ...
 $ online_order           : logi [1:19980] FALSE TRUE FALSE FALSE TRUE TRUE ...
 $ order_status           : chr [1:19980] "Approved" "Approved" "Approved" "Approved" ...
 $ brand                  : chr [1:19980] "Solex" "Trek Bicycles" "OHM Cycles" "Norco Bicycles" ...
 $ product_line           : chr [1:19980] "Standard" "Standard" "Standard" "Standard" ...
 $ product_class          : chr [1:19980] "medium" "medium" "low" "medium" ...
 $ product_size           : chr [1:19980] "medium" "large" "medium" "medium" ...
 $ list_price             : num [1:19980] 71.5 2091.5 1793.4 1198.5 1765.3 ...
 $ standard_cost          : num [1:19980] 53.6 388.9 248.8 381.1 709.5 ...
 $ product_first_sold_date: Date[1:19980], format: "3710138-10-08" "3818007-12-04" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb199"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb199-1"><a href="#cb199-1" aria-hidden="true" tabindex="-1"></a>CustomerDemographic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,997 × 11
   customer_id first_name last_name   gender past_3_years_bike_rela…¹ DOB       
   &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;                     &lt;dbl&gt; &lt;date&gt;    
 1 66          Anselm     Gawne       M                            46 2002-03-11
 2 1888        Sibyl      Scholtz     F                            67 2002-01-26
 3 3435        Stevena    Allcock     F                            80 2002-01-15
 4 2858        Benedicto  Radki       M                             4 2002-01-09
 5 422         Vito       Norker      M                            78 2002-01-06
 6 2296        Nathalia   Sanger      F                            16 2002-01-01
 7 470         Darbee     Klimowicz   M                            22 2001-12-19
 8 3949        Costa      Sleightholm M                            24 2001-12-19
 9 1402        Hillier    Andraud     M                            58 2001-12-08
10 1519        Marwin     Jeyness     M                            35 2001-11-30
# ℹ 3,987 more rows
# ℹ abbreviated name: ¹​past_3_years_bike_related_purchases
# ℹ 5 more variables: job_title &lt;chr&gt;, job_industry_category &lt;chr&gt;,
#   wealth_segment &lt;chr&gt;, owns_car &lt;chr&gt;, tenure &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb201"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb201-1"><a href="#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CustomerDemographic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [3,997 × 11] (S3: tbl_df/tbl/data.frame)
 $ customer_id                        : chr [1:3997] "66" "1888" "3435" "2858" ...
 $ first_name                         : chr [1:3997] "Anselm" "Sibyl" "Stevena" "Benedicto" ...
 $ last_name                          : chr [1:3997] "Gawne" "Scholtz" "Allcock" "Radki" ...
 $ gender                             : chr [1:3997] "M" "F" "F" "M" ...
 $ past_3_years_bike_related_purchases: num [1:3997] 46 67 80 4 78 16 22 24 58 35 ...
 $ DOB                                : Date[1:3997], format: "2002-03-11" "2002-01-26" ...
 $ job_title                          : chr [1:3997] "Account Executive" "Food Chemist" "Senior Editor" "Recruiting Manager" ...
 $ job_industry_category              : chr [1:3997] "Argiculture" "Health" NA NA ...
 $ wealth_segment                     : chr [1:3997] "High Net Worth" "Mass Customer" "Affluent Customer" "Mass Customer" ...
 $ owns_car                           : chr [1:3997] "No" "Yes" "No" "Yes" ...
 $ tenure                             : num [1:3997] 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb203"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb203-1"><a href="#cb203-1" aria-hidden="true" tabindex="-1"></a>CustomerAddress</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,993 × 6
   customer_id address                 postcode state country property_valuation
   &lt;chr&gt;       &lt;chr&gt;                   &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;                &lt;dbl&gt;
 1 1           060 Morning Avenue      2016     NSW   Austra…                 10
 2 2           6 Meadow Vale Court     2153     NSW   Austra…                 10
 3 4           0 Holy Cross Court      4211     QLD   Austra…                  9
 4 5           17979 Del Mar Point     2448     NSW   Austra…                  4
 5 6           9 Oakridge Court        3216     VIC   Austra…                  9
 6 7           4 Delaware Trail        2210     NSW   Austra…                  9
 7 8           49 Londonderry Lane     2650     NSW   Austra…                  4
 8 9           97736 7th Trail         2023     NSW   Austra…                 12
 9 11          93405 Ludington Park    3044     VIC   Austra…                  8
10 12          44339 Golden Leaf Alley 4557     QLD   Austra…                  4
# ℹ 3,983 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb205"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb205-1"><a href="#cb205-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CustomerAddress)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [3,993 × 6] (S3: tbl_df/tbl/data.frame)
 $ customer_id       : chr [1:3993] "1" "2" "4" "5" ...
 $ address           : chr [1:3993] "060 Morning Avenue" "6 Meadow Vale Court" "0 Holy Cross Court" "17979 Del Mar Point" ...
 $ postcode          : chr [1:3993] "2016" "2153" "4211" "2448" ...
 $ state             : chr [1:3993] "NSW" "NSW" "QLD" "NSW" ...
 $ country           : chr [1:3993] "Australia" "Australia" "Australia" "Australia" ...
 $ property_valuation: num [1:3993] 10 10 9 4 9 9 4 12 8 4 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb207"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb207-1"><a href="#cb207-1" aria-hidden="true" tabindex="-1"></a>NewCustomerList</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,000 × 15
   first_name last_name gender past_3_years_bike_related_…¹ DOB        job_title
   &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;                         &lt;dbl&gt; &lt;date&gt;     &lt;chr&gt;    
 1 Chickie    Brister   M                                86 1957-07-12 General …
 2 Morly      Genery    M                                69 1970-03-22 Structur…
 3 Lucine     Stutt     F                                64 1979-01-28 Account …
 4 Melinda    Hadlee    F                                34 1965-09-21 Financia…
 5 Druci      Brandli   F                                39 1951-04-29 Assistan…
 6 Rutledge   Hallt     M                                23 1976-10-06 Compensa…
 7 Nancie     Vian      F                                74 1972-12-27 Human Re…
 8 Duff       Karlowicz M                                50 1972-04-28 Speech P…
 9 Barthel    Docket    M                                72 1985-08-02 Accounti…
10 Rockwell   Matson    M                                94 1995-01-01 Programm…
# ℹ 990 more rows
# ℹ abbreviated name: ¹​past_3_years_bike_related_purchases
# ℹ 9 more variables: job_industry_category &lt;chr&gt;, wealth_segment &lt;chr&gt;,
#   owns_car &lt;chr&gt;, tenure &lt;dbl&gt;, address &lt;chr&gt;, postcode &lt;chr&gt;, state &lt;chr&gt;,
#   country &lt;chr&gt;, property_valuation &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb209"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb209-1"><a href="#cb209-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(NewCustomerList)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,000 × 15] (S3: tbl_df/tbl/data.frame)
 $ first_name                         : chr [1:1000] "Chickie" "Morly" "Lucine" "Melinda" ...
 $ last_name                          : chr [1:1000] "Brister" "Genery" "Stutt" "Hadlee" ...
 $ gender                             : chr [1:1000] "M" "M" "F" "F" ...
 $ past_3_years_bike_related_purchases: num [1:1000] 86 69 64 34 39 23 74 50 72 94 ...
 $ DOB                                : Date[1:1000], format: "1957-07-12" "1970-03-22" ...
 $ job_title                          : chr [1:1000] "General Manager" "Structural Engineer" "Account Representative III" "Financial Analyst" ...
 $ job_industry_category              : chr [1:1000] "Manufacturing" "Property" "Manufacturing" "Financial Services" ...
 $ wealth_segment                     : chr [1:1000] "Mass Customer" "Mass Customer" "Affluent Customer" "Affluent Customer" ...
 $ owns_car                           : chr [1:1000] "Yes" "No" "Yes" "No" ...
 $ tenure                             : num [1:1000] 14 16 5 19 22 8 10 5 17 3 ...
 $ address                            : chr [1:1000] "45 Shopko Center" "14 Mccormick Park" "207 Annamark Plaza" "115 Montana Place" ...
 $ postcode                           : chr [1:1000] "4500" "2113" "4814" "2093" ...
 $ state                              : chr [1:1000] "QLD" "NSW" "QLD" "NSW" ...
 $ country                            : chr [1:1000] "Australia" "Australia" "Australia" "Australia" ...
 $ property_valuation                 : num [1:1000] 6 11 1 9 7 7 5 10 5 6 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb211"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb211-1"><a href="#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the "cleansed data" folder if it doesn't exist</span></span>
<span id="cb211-2"><a href="#cb211-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(<span class="st">"cleansed data"</span>)) {</span>
<span id="cb211-3"><a href="#cb211-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(<span class="st">"cleansed data"</span>)</span>
<span id="cb211-4"><a href="#cb211-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb211-5"><a href="#cb211-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb211-6"><a href="#cb211-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the "subsets" folder inside "cleansed data" if it doesn't exist</span></span>
<span id="cb211-7"><a href="#cb211-7" aria-hidden="true" tabindex="-1"></a>subset_folder <span class="ot">&lt;-</span> <span class="fu">file.path</span>(<span class="st">"cleansed data"</span>, <span class="st">"subsets"</span>)</span>
<span id="cb211-8"><a href="#cb211-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(subset_folder)) {</span>
<span id="cb211-9"><a href="#cb211-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(subset_folder)</span>
<span id="cb211-10"><a href="#cb211-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb211-11"><a href="#cb211-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb211-12"><a href="#cb211-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Export cleansed main files</span></span>
<span id="cb211-13"><a href="#cb211-13" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(CustomerAddress, <span class="st">"cleansed data/CustomerAddress.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb211-14"><a href="#cb211-14" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(CustomerDemographic, <span class="st">"cleansed data/CustomerDemographic.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb211-15"><a href="#cb211-15" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(NewCustomerList, <span class="st">"cleansed data/NewCustomerList.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb211-16"><a href="#cb211-16" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(Transactions, <span class="st">"cleansed data/Transactions.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb211-17"><a href="#cb211-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb211-18"><a href="#cb211-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Export subsets for further analysis</span></span>
<span id="cb211-19"><a href="#cb211-19" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(Customer_0tx_past_yr, <span class="st">"cleansed data/subsets/Customer_0tx_past_yr.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb211-20"><a href="#cb211-20" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(Customer_U_gender, <span class="st">"cleansed data/subsets/Customer_U_gender.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb211-21"><a href="#cb211-21" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(Tx_missing_product_info, <span class="st">"cleansed data/subsets/Tx_missing_product_info.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>